### ISSUE TITLE
White bulb/stripe control

### ISSUE THREAD

**Issue by Oggymator** [mwittig/node-milight-promise#2]
Hi,
is it right, that I can control only RGBW bulbs/stripes?!
I see in the App "EVE" only the 4 zones of the RGBW controller.
Is it possible to Add also the 4 zones of the Single/Dual White controller?
thanks
Oggy

**Comment by mwittig** [comment]
Hi Oggy,

as far as I know this should be possible as there are remote controls with 4-zones for white LEDs - see http://www.amazon.com/LEDENET%C2%AE-Control-Wireless-Dimmable-Controller/dp/B00I09J4P0
I am not sure what the "EVE" App is, but if you use the official control Apps (Milight (iOS) or Mi.Light (Android) you can select a control for the dual white 4-zone controller. See also http://www.milight.com/support#A2 and http://www.milight.com/support#A4
By using the different controls it should also be possible to set-up a mixed-mode configuration,e.g. RGBW on zone1 and DualWhite on zone4.  Hope this helps. Please keep me posted.

**Comment by mwittig** [comment]
no further response

**Comment by mwittig** [comment]
Release 0.0.4 - Added example for WW/CW bulbs/strips
