### ISSUE TITLE
V6: RGB BULBS SINGLE CHANNEL/ZONE

### ISSUE THREAD

**Issue by Steiger04** [mwittig/node-milight-promise#27]
Hi,
for V6:  RGB BULBS SINGLE CHANNEL/ZONE

RgbCommand.prototype.on = function(zone) {
  return [0x31, 0x00, 0x00, 0x05, 0x02, 0x09, 0x00, 0x00, 0x00, 0x01]
};

and

RgbCommand.prototype.off = function(zone) {
  return [0x31, 0x00, 0x00, 0x05, 0x02, 0x0a, 0x00, 0x00, 0x00, 0x01]
};

parameter zone is never used. Is that right?

thx
Carsten

**Comment by mwittig** [comment]
Hi Carsten, yes that's right. As the the command set is for the single-channel RGB Command Control the zone isn't applicable. I'll remove the zone parameter in a future release for clarity. Marcus
