### ISSUE TITLE
Raspberry pi

### ISSUE THREAD

**Issue by chriscartin** [mwittig/node-milight-promise#34]
Really wanted to run this on the pi.

Getting the error below, guessing its because the pi node version is so old (and cant be updated).

Any work around / fix?

Unhandled rejection TypeError: Object function Array() { [native code] } has no method 'from'
    at /home/promise/node_modules/node-milight-promise/src/milight-v6-mixin.js:134:42

**Comment by mwittig** [comment]
@chriscartin Which version of Node.js do you run? You can just type `node --version` to find out. Note, only version 4.x and higher is supported by node-milight-promise.

If you don't use Node.js for other applications my advice is to update your Node.js setup. My advice is NOT to use the Raspbian apt package for nodejs as this will be most likely outdated as you said. Remove the package and install the suitable binary package from https://nodejs.org/en/download/

**Comment by chriscartin** [comment]
The issue is that the pi, by default comes with version v0.10.26. I eventually found a way to install a 'proper' version of node.js but that was only version 6. It seems that's the highest version supported by the ARM6 processor in my Pi so I gave up.

**Comment by mwittig** [comment]
Well, I think the current node.js releases are still supported for ARM6. Please check https://nodejs.org/download/release/v8.9.0/ for available builds of the current LTS release. Later on I will also add further details to get you going.

EDIT: Suggested Setup 
* Make sure node.js is uninstalled and all node processes have been terminated
* Download `node-v8.9.0-linux-armv6l.tar.gz` , e.g. using `curl` or `wget`
* Unpack the downloaded archive, `tar xvfz node-v8.9.0-linux-armv6l.tar.gz`
* Change to the extracted directory, `cd node-v8.9.0-linux-armv6l`
* Copy stuff to `/usr/local`, `sudo cp -R * /usr/local/`

EDIT2: 
> The issue is that the pi, by default comes with version v0.10.26.

You are using an outdated and unsupported version of Raspbian. Newer versions like "Raspbian Stretch" include Node.js version 4, at least. However, as I said the support for Node.js with Raspbian / Debian is not satisfactory in my opinion and this is why my suggestion is to use builds provided by nodejs.org. Note beyond, if you are familiar with Debian Package Management it is also possible to nodejs.org as package source for Raspbian. However, I am not sure this included packaging for ARM6. For this reason my advice goes for using the tar-ball distribution.

**Comment by mwittig** [comment]
No follow up. Closing this now
