### ISSUE TITLE
Support Question

### ISSUE THREAD

**Issue by gemmi-arts** [mwittig/node-milight-promise#52]
Hello,

Does this module support the following controller?

<img width="1136" alt="zrzut ekranu 2018-10-18 o 22 29 37" src="https://user-images.githubusercontent.com/8410173/47182396-9b722580-d325-11e8-909f-b562fb8c94ea.png">

**Comment by mwittig** [comment]
Most likely it does, but I can't tell you for sure as I don't have this device at hand for testing. Note, you'll also need a Milight  Wifi Box to use the controller along with node-milight-promise (or generally to be able to control it with an Internet device like a Smartphone etc). Please let me know about your findings in case you'll give this a try. Thanks

**Comment by mwittig** [comment]
Btw, do you really want to use an RGB controller? 

My recommendation is to use a RGBW controller. This is known to work with `node-milight-promise`  and you can use either RGBW or RGB stripes. The RGB+CCT controller is another option to look at. The price difference for these controller is marginal.

**Comment by mwittig** [comment]
I am closing this now. Please re-open if you wish to follow up on this
