### ISSUE TITLE
How to change bulb temp?

### ISSUE THREAD

**Issue by niv-d** [mwittig/node-milight-promise#53]
Is it possible to change the bulb tempature, I tried whiteTempature but that doesn't seem to work.

**Comment by mwittig** [comment]
Which type of bulb do you have? Are you able to control with "fullColor" commands?

**Comment by niv-d** [comment]
The newest bulbs, with the light hub. Yes I am using the full color command

**Comment by niv-d** [comment]
Nevermind, was throwing invalid values. My bad.
