### ISSUE TITLE
Can somebody help turn zone 5 on/off?

### ISSUE THREAD

**Issue by agoralive** [mwittig/node-milight-promise#60]
Can somebody give me an example on how I turn on zone 5 using this package?

I know this is not "just" a command line, but is there a "simple" way to just do on/off functions?

I am trying to include 8-zone support in Node-Red but that seems like it's impossible, as only 4 zones are supported with all available packages in the "Palette/Install" section.

**Comment by mwittig** [comment]
Thanks for chasing me. Please have a look at the latest version 1.0.8 of node-red-contrib-milight-2

It adds support for the 8-zone controller for full color bulbs.

See also https://github.com/mwittig/node-red-contrib-milight

**Comment by mwittig** [comment]
Btw, a general programming example is given here:
https://github.com/mwittig/node-milight-promise/blob/master/examples/example-8zone-v6.js
