### ISSUE TITLE
New integration for ha-bridge

### ISSUE THREAD

**Issue by maltezacharias** [mwittig/node-milight-promise#70]
Hi,

you asked to create an issue to send you links for new usecases. I have one ;)
I've been using your code for over a year now using ha-bridge and the example scripts that you linked. I've started to dockerize all of my stuff and created this new solution (v6 RGBW only, but easily extendable):

https://github.com/maltezacharias/milight-controller

Basically it uses docker-compose to combine a ha-bridge docker container with another node container that provides a HTTP API for your code, so that calling 

`http://milight-bridge:3000/v6/white/<bridge-ip>/<zone>/<brightness>`

from the ha-bridge container will send a command to the v6 bridge. It only supports on, off, nightlight and white for now, as that's all I really use. But it makes for a clean docker-only install. (There is no authentication there, so it really should only run in an isolated docker network)

Edit: Thanks for providing the code ;) I had already spent a lot of time analyzing the protocol and writing my own, when I found this!

**Comment by mwittig** [comment]
Excellent! Thank you very much for using node-milight-promise and for the link to your project which I have added to references. If you have suggestions for improve please feel to raise an issue or make contributions via PRs.
